[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[build.environment]
  GECC_API_URL = "https://gecc-backend.railway.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://gecc-backend.railway.app/api/:splat"
  status = 200
  force = true
